version = 1

[[watchers]]
name = "karabiner"
path = "~/config/i/karabiner"
match = "karabiner.edn"
command = "~/bin/goku"
debounce_ms = 150
run_on_start = true

[[server]]
name = "1f"
path = "~/src/org/1f/1f"
command = "blade --port 4000"
autostart = true
[server.env]
FORCE_COLOR = "1"

[[server]]
name = "gen"
path = "~/src/org/gen/new"
command = "blade --port 4001"
autostart = true
[server.env]
FORCE_COLOR = "1"

[[server]]
name = "linsa"
path = "~/src/org/linsa/linsa"
command = "blade --port 4002"
autostart = true
[server.env]
FORCE_COLOR = "1"

# [options]
# autofixErrors = true
