version = 1

[options]
trace_terminal_io = true

# [[server]]
# name = "1f"
# path = "~/org/1f/1f"
# command = "blade --port 4000"
# autostart = true
# port = 4000
# [server.env]
# FORCE_COLOR = "1"

# [[server]]
# name = "gen"
# path = "~/org/gen/new"
# command = "bun dev"
# autostart = true
# port = 4001
# [server.env]
# FORCE_COLOR = "1"

# [[server]]
# name = "linsa"
# path = "~/org/linsa/linsa"
# command = "bun dev"
# autostart = true
# port = 4002
# [server.env]
# FORCE_COLOR = "1"

# [[server]]
# name = "agi"
# path = "~/agi"
# command = "flow dev"
# autostart = true
# port = 6000
# [server.env]
# FORCE_COLOR = "1"

[[watchers]]
name = "karabiner"
path = "~/config/i/karabiner"
match = "karabiner.edn"
command = "~/bin/goku"
debounce_ms = 150
run_on_start = true
